#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Generate the mesh
runApplication gmsh -3 mesh/main.geo -o case/test.msh
runApplication gmshToFoam -case case case/test.msh

# Modify the boundary conditions
sed -i '22s/patch/empty/' case/constant/polyMesh/boundary
sed -i '29s/patch/wall/' case/constant/polyMesh/boundary

# Run the solver
runApplication pimpleFoam -case case

# ----------------------------------------------------------------- end-of-file
