#!/bin/sh

gmsh -3 mesh/simple.geo && \
  gmshToFoam mesh/simple.msh && \
  changeDictionary && \
  simpleFoam
  #decomposePar
  #mpirun -np 4 simpleFoam -parallel && \
  #reconstructPar -latestTime

